# Canonical development config for node 2
# This is the known-good baseline config
# Runtime edits are made to corrosion/configs/runtime/node2.toml
[db]
path = "corrosion/dev-node2.db"
schema_paths = ["corrosion/schemas"]

[gossip]
addr = "127.0.0.1:8788"
bootstrap = ["127.0.0.1:8787", "127.0.0.1:8789"]
plaintext = true

[api]
addr = "127.0.0.1:8082"

[admin]
path = "/tmp/corrosion/node2_admin.sock"
