# Canonical development config for node 1
# This is the known-good baseline config
# Runtime edits are made to corrosion/configs/runtime/node1.toml
[db]
path = "corrosion/dev-node1.db"
schema_paths = ["corrosion/schemas"]

[gossip]
addr = "127.0.0.1:8787"
bootstrap = ["127.0.0.1:8788", "127.0.0.1:8789"]
plaintext = true

[api]
addr = "127.0.0.1:8081"

[admin]
path = "/tmp/corrosion/node1_admin.sock"
